### ISSUE TITLE
¿Son todos los requisitos que salen en la documentación del proyecto funcionales?

### ISSUE THREAD

**Issue by AlejandroFernandezMunoz** [AlejandroFernandezMunoz/ISO2-LAB-C03#1]
Al revisar la documentación del proyecto nos ha surgido una duda respecto a los requisitos que se han descrito.

En la lista de requisitos del proyecto se mencionan varios elementos, pero no estamos seguros de si todos los requisitos que se incluyen son funcionales, o si hay algunos que deberían ser considerados **requisitos no funcionales**.  

Y a colación de esto, ¿es necesario incluir un apartado **Requisitos No Funcionales** en la wiki de la Iteración 0? Por defecto se ha añadido, pero no sabemos si sea mejor quitarlo.

**Comment by Lugs72** [comment]
Respecto a la pregunta de si todos los requisitos de la documentación del proyecto son funcionales, la respuesta es no.
En este proyecto existen requisitos no funcionales, que son especificaciones que definen cómo debe ser el sistema o cómo debe comportarse, en lugar de describir una funcionalidad concreta que el sistema debe realizar. Por ejemplo, se menciona que el software desarrollado debe ser multidispositivo, seguir una arquitectura cliente/servidor y garantizar mantenibilidad y escalabilidad.
Respecto a la pregunta sobre incluir estos requisitos en la wiki, sí, es recomendable incluirlos. Son clave para orientar el desarrollo y asegurar calidad y rendimiento. Documentarlos desde el inicio ayuda a prevenir problemas futuros.
