### ISSUE TITLE
¿Es necesario que haya un número determinado de CDUs por cada integrante del grupo?

### ISSUE THREAD

**Issue by AlejandroFernandezMunoz** [AlejandroFernandezMunoz/ISO2-LAB-C03#2]
Durante el mapeo de casos de uso a partir de los requisitos funcionales que hemos extraído, nos ha surgido la duda de si es necesario que haya un número específico de casos de uso para cada uno de los miembros del grupo, es decir, ¿tiene que haber, por ejemplo, 2 CDU por cada miembro del grupo?

**Comment by Lugs72** [comment]
Debería haber, como mínimo un CDU por integrante. No existe un límite máximo de CDU, pero si el número es demasiado alto, es importante considerar el tiempo total que requeriría completarlos, ya que el proyecto tiene una fecha límite. Por ello, es recomendable encontrar un equilibrio en la cantidad de casos de uso para asegurar que el proyecto pueda finalizarse a tiempo.
