### ISSUE TITLE
¿Es necesario añadir una serie de requisitos funcionales adicionales a los CDUs existentes?

### ISSUE THREAD

**Issue by AlejandroFernandezMunoz** [AlejandroFernandezMunoz/ISO2-LAB-C03#3]
Nos ha surgido durante el mapeo de casos de uso la duda de si es necesario añadir más requisitos funcionales de los que se listan en la documentación de la práctica.

Y a raíz de eso, si tras analizarlo encontrásemos oportuno añadir n requisitos, ¿deberíamos consultarlo con los profesores antes de añadirlos a los respectivos casos de uso?

**Comment by AlejandroFernandezMunoz** [comment]
Belén realiza la siguiente lista de posibles RF que podrían ser considerados para añadirlos a cada uno de los casos de uso:
[RF_adicionales.pdf](https://github.com/user-attachments/files/17480410/LISTA.DE.RECURSOS.FUNCIONALES.ADICIONALES.PARA.CADA.CASO.DE.USO.pdf)

**Comment by Lugs72** [comment]
Dado que se está implementando una arquitectura cliente/servidor, es probable que surjan nuevas necesidades que requieran la inclusión de requisitos adicionales. Por lo tanto, si se considera que hay funcionalidades importantes que deben añadirse, es recomendable consultarlo con los profesores antes de hacerlo.
