### ISSUE TITLE
¿Es necesario que la fecha de finalización del proyecto cuadre con la fecha real de entrega de la práctica en el laboratorio?

### ISSUE THREAD

**Issue by AlejandroFernandezMunoz** [AlejandroFernandezMunoz/ISO2-LAB-C03#4]
Al hacer la planificación con las horas y las prioridades asignadas en un principio, la fecha de finalización del proyecto se estima que sea el 29/01, lo cuál dista bastante de la fecha real de entrega de la práctica. 

Por tanto, ¿tiene que ser la fecha de finalización la misma que la de entrega o al menos estar cerca, o es irrelevante?

Si no importase, entonces entendemos que las fechas de cada iteración no se pueden tomar como una guía real, si no simplemente como algo hipotético, ¿no?

**Comment by Lugs72** [comment]
La fecha de finalización del proyecto debe coincidir o estar muy cerca de la fecha de entrega establecida, ya que el proyecto debe estar completado para ese día. Es posible terminarlo unos días antes de la entrega, pero no después.
