### ISSUE TITLE
¿Es óptimo el número de casos de uso extraído o debería ser mayor/menor?

### ISSUE THREAD

**Issue by AlejandroFernandezMunoz** [AlejandroFernandezMunoz/ISO2-LAB-C03#5]
Hemos extraído 9 CDUs de los requisitos funcionales presentes en la documentación. 
¿Son demasiados requisitos, o por el contrario deberían ser más?

**Comment by Lugs72** [comment]
El número de casos de uso extraídos no es óptimo. Lo ideal sería tener alrededor de uno por cada miembro del grupo.
