### ISSUE TITLE
¿Se prefiere tener un diagrama de casos de uso global o varios más individualizados?

### ISSUE THREAD

**Issue by eliasgv04** [AlejandroFernandezMunoz/ISO2-LAB-C03#6]
Hemos realizado nuestro diagrama de casos de uso global con todos los actores y casos de uso pero no sabemos si es más correcto hacer individualizado por actores.

**Comment by Lugs72** [comment]
Sería recomendable crear diagramas de casos de uso individualizados por actores, ya que esto permite una mejor comprensión de las interacciones específicas y facilita la identificación de las necesidades y expectativas de cada actor, aclarando así la funcionalidad del sistema de manera más detallada.
